/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tombalaproject;

import java.util.Random;
import javax.swing.JFrame;

/**
 *
 * @author GIGABYTE
 */
public class Bahar_Karakas_MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public Bahar_Karakas_MainFrame() {
        initComponents();
        
        
        //jButton1ActionPerformed(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Add a Player");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Start the Game");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tombala");

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("To start the game, add at least 1 player");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Auto Draw");

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Auto Mark Cards");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox2)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(117, 117, 117))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addGap(146, 146, 146))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(99, 99, 99)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static Random random = new Random();
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        Bahar_Karakas_TombalaLinkedList<Bahar_Karakas_TombalaNumber> cardNumbers = new Bahar_Karakas_TombalaLinkedList<>();
        
        for (int i = 0; i < 3; i++) {
            for (int x = 0; x < 5; x++) {
                
                int maxBoundry = (5+x)*10;
                
                int num = random.nextInt((x == 0) ? 1 : ((Math.floorDiv(cardNumbers.getLastElement().number, 10) + 1) * 10), maxBoundry);
                Bahar_Karakas_TombalaNumber number = new Bahar_Karakas_TombalaNumber(num);
                if (cardNumbers.contains(number)) {
                    x--;
                    continue;
                }
                
                cardNumbers.addToList(number);
            }
        }
        
        
        
       sortArray(cardNumbers);
       sortArray(cardNumbers);
        
        
        int possibleName = 0;
        for(var x = 0; x < players.getSize(); x++) {
            int thisName = players.getAt(x).name;
            if(possibleName <= thisName) possibleName = thisName + 1;
        }
        
        final Bahar_Karakas_TombalaCard card = new Bahar_Karakas_TombalaCard();
        players.addToList(card);
        card.setVisible(true);
        card.setNumbers(cardNumbers);
        card.setPlayerName(possibleName);
        
        card.setOnWinAction( new Bahar_Karakas_OnDispose() {
            @Override
            public void onPlayerDispose() {
                setWinner(card);
            }
        });
        
        card.setDisposeCallback(new Bahar_Karakas_OnDispose() {
            @Override
            public void onPlayerDispose() {
                
                players.removeFromList(card);
                
                if(!gameStarted && players.getSize() <= 0) {
                    jButton2.setEnabled(false);
                    jLabel2.setVisible(true);
                }
            }
        });
       
        jButton2.setEnabled(true);
        jLabel2.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    void sortArray(Bahar_Karakas_TombalaLinkedList<Bahar_Karakas_TombalaNumber> cardNumbers) {
         for(int i = 0; i < cardNumbers.getSize(); i++) {
            
            Bahar_Karakas_TombalaNumber myNumber = cardNumbers.getAt(i);
        
            for(int x = i; x < cardNumbers.getSize(); x++) {
                if(x == i) continue;
                 Bahar_Karakas_TombalaNumber compareNumber = cardNumbers.getAt(x);
                 
                 
                 if(Math.floor(myNumber.number/10) == Math.floor(compareNumber.number/10) && myNumber.number > compareNumber.number) {
                     System.out.println("Switching " + myNumber.number + " with " + compareNumber.number);
                        cardNumbers.replaceElement(x, myNumber);
                     cardNumbers.replaceElement(i, compareNumber);
                     break;
                 }
            }
        }
    }
    
    public void setWinner(Bahar_Karakas_TombalaCard winner) {
        for(int i = 0; i < players.getSize(); i++) {
            players.getAt(i).setWinner(winner);
        }
        
        
    }
    
    public boolean isAutoDraw() {
        return jCheckBox1.isSelected();
    }
    
    public boolean isAutoMark() {
        return jCheckBox2.isSelected();
    }
    
    public boolean gameStarted;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        for(int i = 0; i < players.getSize(); i++) {
            players.getAt(i).gameStarted = true;
            players.getAt(i).autoDraw = isAutoMark();
        }
        Bahar_Karakas_TombalaGame game = new Bahar_Karakas_TombalaGame();
        game.setPlayers(players, this);
game.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b); 
        
        if(b) {
        Bahar_Karakas_TombalaLinkedList<Bahar_Karakas_TombalaCard> oldPlayerList = players;
       
        for(int i = 0; i < oldPlayerList.getSize(); i++) {
            oldPlayerList.getAt(i).setDisposeCallback(new Bahar_Karakas_OnDispose() {
                @Override
                public void onPlayerDispose() {
                    
                }
            });
            oldPlayerList.getAt(i).dispose();
        }
        
        players = new Bahar_Karakas_TombalaLinkedList<>();
        
        jButton2.setEnabled(false);
        jLabel2.setVisible(true);
        }
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bahar_Karakas_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bahar_Karakas_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bahar_Karakas_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bahar_Karakas_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bahar_Karakas_MainFrame().setVisible(true);
            }
        });
    }
    
    
    
    
    public Bahar_Karakas_TombalaLinkedList<Bahar_Karakas_TombalaCard> players = new Bahar_Karakas_TombalaLinkedList<>();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
